name: htmlize

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: kopinions/ohtmlize:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
    # - name: setup debug session
    #  uses: mxschmitt/action-tmate@v2
      - name: hexo build
        run: |
          npm install
          npm run clean
          npm run generate
      - name: deploy
        env:
          PUTUTU_ACCESS_TOKEN_GITHUB: ${{ secrets.PUTUTU_ACCESS_TOKEN_GITHUB }}
          PUTUTU_ACCESS_TOKEN_GITEE: ${{ secrets.PUTUTU_ACCESS_TOKEN_GITEE }}
        run: |
          npm run deploy -- --debug
